server:
  port: 8080
  tomcat:
    max-threads: 200
    min-spare-threads: 10
  
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 添加安全配置
security:
  basic:
    enabled: true
  user:
    name: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:changeit} 