server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  storage:
    upload-dir: ./uploads
    processed-dir: ./processed
    temp-dir: ./temp
    duplicate-dir: ./duplicate

logging:
  file:
    name: ./logs/app.log
  level:
    root: INFO
    com.example.invoice: DEBUG